### ISSUE TITLE
Provise Sass/Scss version of styles

### ISSUE THREAD

**Issue by farskid** [shakrmedia/petal#3]
Hi there folks, Thanks for the effort to create such a nice boilerplate.
As SASS/SCSS is more adopted and accepted among developers, It would be nice to have a scss version of styles. I'd be glad to contribute for the scss version.

**Comment by zvuc** [comment]
Hi!
We made Petal in LESS because that was the preprocessor we use internally in Shakr. While we don't have any plans to make a SASS version now, you're welcome to fork and make a SASS version of Petal. Mind that we probably won't be able to host and manage both versions, so you'll probably have to maintain as a separate repository. When you do make one, let us know and we'll link it in the readme and documentation. :)

**Comment by farskid** [comment]
Thanks for the clarification. I already forked the repo at https://github.com/farskid/petal and will work on the SCSS version of it. once the first stable release is out, I'll notify for the link in documentations. Thanks in advance!

**Comment by zvuc** [comment]
Closing since we still don't have a plan to switch to Sass in near future. That said, we're open for contributions so if anyone wants to take over again you're welcome to do so!
